{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "ods.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  {{- if .Values.serviceAccount.annotations }}
  annotations: {{ tpl (toYaml .Values.serviceAccount.annotations) . | nindent 4 }}
  {{- end }}
  labels: {{ include "ods.labels" . | nindent 4 }}
{{- end -}}
